# Generated by Django 4.1.7 on 2023-10-14 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AccountingWallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("provider", models.PositiveSmallIntegerField()),
                ("provider_name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "accounting_wallet",
                "unique_together": {("address", "provider")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=255)),
                ("market", models.CharField(max_length=255)),
                ("type", models.PositiveSmallIntegerField()),
                ("type_name", models.CharField(max_length=255)),
                ("side", models.PositiveSmallIntegerField()),
                ("side_name", models.CharField(max_length=255)),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=255)),
                ("original_size", models.FloatField()),
                ("remaining_size", models.FloatField()),
                ("order_timestamp", models.BigIntegerField()),
                ("order_created_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.accountingwallet",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_order",
            },
        ),
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=255)),
                ("status", models.PositiveSmallIntegerField()),
                ("status_name", models.CharField(max_length=255)),
                ("side", models.PositiveSmallIntegerField()),
                ("side_name", models.CharField(max_length=255)),
                ("size", models.FloatField()),
                ("remaining_size", models.FloatField()),
                ("unrealized_pnl", models.FloatField()),
                ("realized_pnl", models.FloatField()),
                ("position_created_at", models.DateTimeField()),
                ("position_closed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.accountingwallet",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_trade_position",
            },
        ),
        migrations.CreateModel(
            name="OrderFill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.FloatField()),
                ("size", models.FloatField()),
                ("fee", models.FloatField()),
                ("closed_pnl", models.FloatField()),
                ("side", models.PositiveSmallIntegerField()),
                ("side_name", models.CharField(max_length=255)),
                ("direction", models.PositiveSmallIntegerField(null=True)),
                ("direction_name", models.CharField(max_length=255, null=True)),
                ("position_side", models.PositiveSmallIntegerField()),
                ("position_side_name", models.CharField(max_length=255)),
                ("hash", models.CharField(max_length=255, null=True)),
                ("order_fill_timestamp", models.BigIntegerField()),
                ("order_fill_created_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orderfills",
                        to="src.order",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_order_fill",
            },
        ),
        migrations.CreateModel(
            name="FundingPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market", models.CharField(max_length=255)),
                ("payment", models.FloatField()),
                ("funding_rate", models.FloatField()),
                ("position_size", models.FloatField()),
                ("hash", models.CharField(max_length=255, null=True)),
                ("funding_timestamp", models.BigIntegerField()),
                ("funding_created_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.accountingwallet",
                    ),
                ),
            ],
            options={
                "db_table": "accounting_funding_payment",
            },
        ),
    ]
