# Generated by Django 4.1.7 on 2023-10-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0002_walletportfolio"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="value",
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
    ]
