# Generated by Django 4.1.7 on 2024-04-21 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0003_position_value"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaoshiPosition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position_uuid", models.CharField(max_length=255, unique=True)),
                ("average_entry_price", models.FloatField()),
                ("close_time", models.DateTimeField(null=True)),
                ("open_time", models.DateTimeField()),
                ("current_return", models.FloatField()),
                ("initial_entry_price", models.FloatField()),
                ("is_closed", models.BooleanField()),
                ("net_leverage", models.FloatField()),
                ("miner", models.PositiveSmallIntegerField()),
                ("miner_name", models.CharField(max_length=255)),
                ("position_type", models.CharField(max_length=255)),
                ("return_at_close", models.FloatField()),
                ("base_currency", models.CharField(max_length=255)),
                ("counter_currency", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "signals_taoshi_position",
            },
        ),
        migrations.CreateModel(
            name="TaoshiPositionOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_uuid", models.CharField(max_length=255, unique=True)),
                ("leverage", models.FloatField()),
                ("processed_time", models.DateTimeField(null=True)),
                ("order_type", models.CharField(max_length=255)),
                ("price", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="src.taoshiposition",
                    ),
                ),
            ],
            options={
                "db_table": "signals_taoshi_position_order",
            },
        ),
    ]
