# Generated by Django 4.1.7 on 2024-04-21 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0004_taoshiposition_taoshipositionorder"),
    ]

    operations = [
        migrations.RenameField(
            model_name="taoshipositionorder",
            old_name="wallet",
            new_name="position",
        ),
    ]
