# Generated by Django 4.1.7 on 2024-04-21 07:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0005_rename_wallet_taoshipositionorder_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="taoshiposition",
            name="miner_public_key",
            field=models.CharField(default="test", max_length=255),
            preserve_default=False,
        ),
    ]
