# Generated by Django 4.1.7 on 2024-04-22 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("src", "0007_remove_taoshiposition_miner_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="taoshipositionorder",
            name="market_price",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
